// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() int
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func (User) IsNode()         {}
func (this User) GetID() int { return this.ID }
